apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config
  namespace: my-namespace
data:
  nginx.conf: |
    worker_processes  1;

    events {
      worker_connections  1024;
    }

    http {
      server {
        listen       8000;
        server_name  localhost;

        location = /conf/file {
          alias   /etc/nginx/nginx.conf;
          add_header Content-Type text/plain;
        }

        location / {
          root   /homework;
          index  index.html;
        }
      }
    }