apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress-conf
  namespace: my-namespace
spec:
  ingressClassName: nginx
  rules:
    - host: {{.Values.host}}
      http:
        paths:
          - path: /conf/file
            pathType: Exact
            backend:
              service:
                name: my-service
                port:
                  name: web