apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: my-rolebinding-cd
  namespace: my-namespace
subjects:
  - kind: ServiceAccount
    name: my-serviceaccount-cd
    apiGroup: ""
roleRef:
  kind: Role
  name: my-role-cd
  apiGroup: rbac.authorization.k8s.io