apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  namespace: namespace
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      name: deployment
  template:
    metadata:
      labels:
        name: deployment
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: homework
                    operator: In
                    values:
                      - "true"
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                  - key: homework
                    operator: In
                    values:
                      - "true"
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: volume
              mountPath: /homework/
            - name: config
              mountPath: /etc/nginx/
          lifecycle:
            preStop:
              exec:
                command: [ 'rm', '/homework/index.html' ]
          readinessProbe:
            httpGet:
              port: 8000
            timeoutSeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              port: 8000
            timeoutSeconds: 5
            periodSeconds: 5
      initContainers:
        - name: init
          image: busybox:1.28
          command: [ 'touch', '/init/index.html' ]
          volumeMounts:
            - name: volume
              mountPath: /init/
      volumes:
        - name: volume
          emptyDir:
            sizeLimit: 10Mi
        - name: config
          configMap:
            name: config
            items:
              - key: nginx.conf
                path: "nginx.conf"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: namespace
data:
  nginx.conf: |
    worker_processes  1;

    events {
      worker_connections  1024;
    }

    http {
      server {
        listen       8000;
        server_name  localhost;

        location / {
          root   /homework;
          index  index.html;
        }
      }
    }