apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: namespace
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: {{.Values.host}}
      http:
        paths:
          - path: /(homepage)?$
            pathType: Prefix
            backend:
              service:
                name: service
                port:
                  name: web