apiVersion: v1
kind: Service
metadata:
  name: service
  namespace: namespace
  labels:
    name: service
spec:
  type: ClusterIP
  selector:
    name: deployment
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      name: web