apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: my-rolebinding-monitoring
  namespace: my-namespace
subjects:
  - kind: ServiceAccount
    name: my-serviceaccount-monitoring
    namespace: my-namespace
    apiGroup: ""
roleRef:
  kind: ClusterRole
  name: my-role-monitoring
  apiGroup: rbac.authorization.k8s.io