apiVersion: v1
kind: Pod
metadata:
  name: my-curl
  namespace: my-namespace
spec:
  serviceAccountName: my-serviceaccount-monitoring
  automountServiceAccountToken: true
  containers:
    - image: curlimages/curl:8.9.1
      command:
        - sleep
        - "3600"
      imagePullPolicy: IfNotPresent
      name: busybox
  restartPolicy: Always