apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-persistentvolume
  namespace: my-namespace
spec:
  storageClassName: default
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{.Values.hostPath}}