apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: namespace
spec:
  containers:
    - name: nginx
      image: nginx:1.14.2
      ports:
        - containerPort: 8000
      volumeMounts:
        - name: volume
          mountPath: /homework/
        - name: config
          mountPath: /etc/nginx/
      lifecycle:
        preStop:
          exec:
            command: [ 'rm', '/homework/index.html' ]
  initContainers:
    - name: init
      image: busybox:1.28
      command: [ 'touch', '/init/index.html' ]
      volumeMounts:
        - name: volume
          mountPath: /init/
  volumes:
    - name: volume
      emptyDir:
        sizeLimit: 10Mi
    - name: config
      configMap:
        name: config
        items:
          - key: nginx.conf
            path: "nginx.conf"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: namespace
data:
  nginx.conf: |
    worker_processes  1;
    
    events {
      worker_connections  1024;
    }
    
    http {      
      server {
        listen       80;
        server_name  localhost;
    
        location / {
          root   /homework;
          index  index.html;
        }
      }
    }
    
